window.reveal = {
	ip: '73.15.160.160',
	domain: 'koop.codes',
	fuzzy: true,
	company: {
		id: '79087497-331e-4ff6-958d-4d4d25e6041a',
		name: 'Koop',
		legalName: null,
		domain: 'koop.codes',
		domainAliases: [],
		url: 'http://koop.codes',
		site: {
			url: 'http://koop.codes',
			title: 'Koop Codes',
			h1: 'Koop Codes',
			metaDescription: 'Koopz Web Development Portfolio',
			metaAuthor: 'Koop',
			phoneNumbers: [],
			emailAddresses: ['koop@koop.codes'],
		},
		category: {
			sector: null,
			industryGroup: null,
			industry: null,
			subIndustry: null,
			sicCode: null,
			naicsCode: null,
		},
		tags: [],
		description:
			"I'm a former HP Data Analyst renewing my IT career as a full stack web developer. I eat code for breakfast 👨‍💻🥣",
		foundedYear: null,
		location: null,
		timeZone: null,
		utcOffset: null,
		geo: {
			streetNumber: null,
			streetName: null,
			subPremise: null,
			city: null,
			postalCode: null,
			state: null,
			stateCode: null,
			country: null,
			countryCode: null,
			lat: null,
			lng: null,
		},
		logo: 'https://logo.clearbit.com/koop.codes',
		facebook: { handle: null },
		linkedin: { handle: null },
		twitter: {
			handle: 'koopdev',
			id: '51145868',
			bio:
				"I'm a former HP Data Analyst renewing my IT career as a full stack web developer. I eat code for breakfast 👨‍💻🥣",
			followers: 83,
			following: 160,
			location: 'Campbell, CA, USA, NA, Earth',
			site: 'https://t.co/mzbJXZyqA6',
			avatar:
				'https://pbs.twimg.com/profile_images/989574158890618880/VJkxnqce_normal.jpg',
		},
		crunchbase: { handle: null },
		emailProvider: false,
		type: 'private',
		ticker: null,
		phone: null,
		metrics: {
			alexaUsRank: null,
			alexaGlobalRank: 12455613,
			employees: null,
			employeesRange: null,
			marketCap: null,
			raised: null,
			annualRevenue: null,
			estimatedAnnualRevenue: null,
			fiscalYearEnd: null,
		},
		tech: ['nginx', 'google_tag_manager', 'google_analytics'],
		parent: { domain: null },
	},
};
